# Generated by Django 3.0.6 on 2020-05-29 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SSHSourcePlugin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.SlugField(blank=True, help_text='Internal name, leave empty to autopopulate.', max_length=64, unique=True, verbose_name='Name')),
                ('title', models.CharField(help_text='Verbose name for display purposes', max_length=256, verbose_name='Title')),
                ('shell', models.CharField(default='/bin/bash', help_text='This is usually /bin/bash on linux.', max_length=256, verbose_name='Remote Shell')),
                ('content', models.CharField(default='echo 1', help_text='Put the script content here.  It will be executed by the shell you select.', max_length=4096, verbose_name='The Script')),
            ],
            options={
                'verbose_name': 'SSH Source',
                'verbose_name_plural': 'SSH Sources',
            },
        ),
    ]
