# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-12-12 22:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SSHSourcePlugin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name',
                 models.SlugField(blank=True, help_text='Internal name, leave empty to autopopulate.', max_length=64,
                                  unique=True, verbose_name='Name')),
                ('title',
                 models.CharField(help_text='Verbose name for display purposes', max_length=256, verbose_name='Title')),
                ('shell', models.CharField(help_text='This is usually /bin/bash on linux.', max_length=256,
                                           verbose_name='Remote Shell')),
                ('content', models.CharField(default='#!/bin/bash\n',
                                             help_text='Put the script content here.  It will be executed by the shell you select.',
                                             max_length=4096, verbose_name='The Script')),
            ],
            options={
                'verbose_name_plural': 'SSH Sources',
                'verbose_name': 'SSH Source',
            },
        ),
    ]
