# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-12-12 22:50
from __future__ import unicode_literals

from django.db import migrations


def forwards_func(apps, schema_editor):
    # We get the model from the versioned app registry;
    # if we directly import it, it'll be the wrong version
    SSHSourcePlugin = apps.get_model("SSHSourcePlugin", "SSHSourcePlugin")
    SourcePlugin = apps.get_model('System', 'SourcePlugin')
    ContentType = apps.get_model('contenttypes', 'ContentType')

    db_alias = schema_editor.connection.alias
    SSHSourcePlugin.objects.using(db_alias).create(pk=1, name='ssh-exec', title="Execute through SSH",
                                                   shell='/bin/bash', content='echo test')
    SourcePlugin.objects.using(db_alias).create(id=1, name='(SSHSourcePlugin) SSH Remote Shell', object_id=1,
                                                content_type=ContentType.objects.get(pk=27))


def reverse_func(apps, schema_editor):
    # forwards_func() creates two Country instances,
    # so reverse_func() should delete them.
    SSHSourcePlugin = apps.get_model("SSHSourcePlugin", "SSHSourcePlugin")
    SourcePlugin = apps.get_model('System', 'SourcePlugin')
    db_alias = schema_editor.connection.alias

    SSHSourcePlugin.objects.using(db_alias).get(pk=1).delete()
    SourcePlugin.objects.using(db_alias).get(id=1).delete()


class Migration(migrations.Migration):
    dependencies = [
        ('SSHSourcePlugin', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_func),
    ]
