# Generated by Django 3.0.6 on 2020-05-29 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SNMPSourcePlugin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.SlugField(blank=True, help_text='Internal name, leave empty to autopopulate.', max_length=64, unique=True, verbose_name='Name')),
                ('title', models.CharField(help_text='Verbose name for display purposes', max_length=256, verbose_name='Title')),
                ('oid', models.CharField(help_text='Enter the OID you wish to poll, in dotted number form.', max_length=256, verbose_name='The OID')),
                ('version', models.CharField(choices=[('1', 'Version 1'), ('2c', 'Version 2c'), ('3', 'Version 3')], default='1', help_text='Select the SNMP version the remote assets is configured to use.', max_length=8, verbose_name='SNMP Version')),
            ],
            options={
                'verbose_name': 'SNMP Source',
                'verbose_name_plural': 'SNMP Sources',
            },
        ),
    ]
