# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-12-12 20:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SNMPSourcePlugin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name',
                 models.SlugField(blank=True, help_text='Internal name, leave empty to autopopulate.', max_length=64,
                                  unique=True, verbose_name='Name')),
                ('title',
                 models.CharField(help_text='Verbose name for display purposes', max_length=256, verbose_name='Title')),
                ('oid',
                 models.CharField(help_text='Enter the OID you wish to poll, in dotted number form.', max_length=256,
                                  verbose_name='The OID')),
                ('version',
                 models.CharField(choices=[('1', 'Version 1'), ('2c', 'Version 2c'), ('3', 'Version 3')], default='1',
                                  help_text='Select the SNMP version the remote assets is configured to use.',
                                  max_length=8, verbose_name='SNMP Version')),
            ],
            options={
                'verbose_name_plural': 'SNMP Sources',
                'verbose_name': 'SNMP Source',
            },
        ),
    ]
