# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-12-12 20:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BooleanThresholdTriggerPlugin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name',
                 models.SlugField(blank=True, help_text='Internal name, leave empty to autopopulate.', max_length=64,
                                  unique=True, verbose_name='Name')),
                ('title',
                 models.CharField(help_text='Verbose name for display purposes', max_length=256, verbose_name='Title')),
                ('datatype', models.CharField(
                    choices=[('number', 'Number'), ('string', 'Character String'), ('boolean', 'Booleans')],
                    default='boolean', editable=False, help_text='The data datatype this trigger supports.',
                    max_length=8, verbose_name='Data Type')),
                ('boolean_good',
                 models.CharField(blank=True, max_length=4096, verbose_name='Alert When Boolean Does Not Match')),
                ('boolean_bad',
                 models.CharField(blank=True, max_length=4096, verbose_name='Alert When Boolean Matches')),
            ],
            options={
                'verbose_name_plural': 'Boolean Thresholds',
                'verbose_name': 'Boolean Threshold',
            },
        ),
        migrations.CreateModel(
            name='NumberThresholdTriggerPlugin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name',
                 models.SlugField(blank=True, help_text='Internal name, leave empty to autopopulate.', max_length=64,
                                  unique=True, verbose_name='Name')),
                ('title',
                 models.CharField(help_text='Verbose name for display purposes', max_length=256, verbose_name='Title')),
                ('datatype', models.CharField(
                    choices=[('number', 'Number'), ('string', 'Character String'), ('boolean', 'Booleans')],
                    default='number', editable=False, help_text='The data datatype this trigger supports.',
                    max_length=8, verbose_name='Data Type')),
                ('number_low', models.CharField(blank=True, max_length=4096, verbose_name='Alert When Number Under')),
                ('number_high', models.CharField(blank=True, max_length=4096, verbose_name='Alert When Number Above')),
            ],
            options={
                'verbose_name_plural': 'Number Thresholds',
                'verbose_name': 'Number Threshold',
            },
        ),
        migrations.CreateModel(
            name='StringThresholdTriggerPlugin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name',
                 models.SlugField(blank=True, help_text='Internal name, leave empty to autopopulate.', max_length=64,
                                  unique=True, verbose_name='Name')),
                ('title',
                 models.CharField(help_text='Verbose name for display purposes', max_length=256, verbose_name='Title')),
                ('datatype', models.CharField(
                    choices=[('number', 'Number'), ('string', 'Character String'), ('boolean', 'Booleans')],
                    default='string', editable=False, help_text='The data datatype this trigger supports.',
                    max_length=8, verbose_name='Data Type')),
                ('string_good',
                 models.CharField(blank=True, max_length=4096, verbose_name='Alert When String Does Not Match')),
                ('string_bad', models.CharField(blank=True, max_length=4096, verbose_name='Alert When String Matches')),
            ],
            options={
                'verbose_name_plural': 'String Thresholds',
                'verbose_name': 'String Threshold',
            },
        ),
    ]
