# Generated by Django 3.0.6 on 2020-07-10 21:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.SlugField(blank=True, help_text='Internal name, leave empty to autopopulate.', max_length=64, unique=True, verbose_name='Email Template Name')),
                ('title', models.CharField(help_text='Verbose name for display purposes', max_length=256, verbose_name='Email Template Title')),
            ],
            options={
                'verbose_name': 'Template',
                'verbose_name_plural': 'Email Templates',
                'ordering': ['-name'],
            },
        ),
        migrations.CreateModel(
            name='EmailAlertHookPlugin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.SlugField(blank=True, help_text='Internal name, leave empty to autopopulate.', max_length=64, unique=True, verbose_name='Name')),
                ('title', models.CharField(help_text='Verbose name for display purposes', max_length=256, verbose_name='Title')),
                ('recipients', models.CharField(blank=True, help_text='Email addresses that will receive the alerts.  Separate with a comma.', max_length=256, verbose_name='Recipients List')),
                ('template_error', models.ForeignKey(help_text='Choose or create an email template.  You can use django templating.', on_delete=django.db.models.deletion.CASCADE, related_name='template_error', to='EmailAlertHookPlugin.EmailTemplate', verbose_name='Email Template when an error is raised.')),
                ('template_failing', models.ForeignKey(help_text='Choose or create an email template.  You can use django templating.', on_delete=django.db.models.deletion.CASCADE, related_name='template_failing', to='EmailAlertHookPlugin.EmailTemplate', verbose_name='Email Template when a fail is trigger.')),
                ('template_recovered', models.ForeignKey(help_text='Choose or create an email template.  You can use django templating.', on_delete=django.db.models.deletion.CASCADE, related_name='template_recovered', to='EmailAlertHookPlugin.EmailTemplate', verbose_name='Email Template when recovering.')),
            ],
            options={
                'verbose_name': 'Email Alert',
                'verbose_name_plural': 'Email Alerts',
            },
        ),
    ]
