# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-12-12 22:12
from __future__ import unicode_literals

from django.db import migrations


def forwards_func(apps, schema_editor):
    # We get the model from the versioned app registry;
    # if we directly import it, it'll be the wrong version
    EmailAlertHookPlugin = apps.get_model("EmailAlertHookPlugin", "EmailAlertHookPlugin")
    EmailTemplate = apps.get_model("EmailAlertHookPlugin", "EmailTemplate")
    HookPlugin = apps.get_model('System', 'HookPlugin')
    ContentType = apps.get_model('contenttypes', 'ContentType')

    db_alias = schema_editor.connection.alias
    EmailTemplate.objects.using(db_alias).create(pk=1, name='full-details', title='Full Details')
    detailedTemplate = EmailTemplate.objects.get(pk=1)
    EmailAlertHookPlugin.objects.using(db_alias).create(pk=1, name='send-alert-to-sysops', title="Send alert to sysops",
                                                        recipients='sysops@example.com',
                                                        template_failing=detailedTemplate,
                                                        template_recovered=detailedTemplate,
                                                        template_error=detailedTemplate)
    HookPlugin.objects.using(db_alias).create(id=1, name='(EmailAlertHookPlugin) Email Alerting', object_id=1,
                                              content_type=ContentType.objects.get(model='emailalerthookplugin'))


def reverse_func(apps, schema_editor):
    # forwards_func() creates two Country instances,
    # so reverse_func() should delete them.
    EmailAlertHookPlugin = apps.get_model("EmailAlertHookPlugin", "EmailAlertHookPlugin")
    EmailTemplate = apps.get_model("EmailAlertHookPlugin", "EmailTemplate")
    HookPlugin = apps.get_model('System', 'HookPlugin')
    db_alias = schema_editor.connection.alias

    EmailAlertHookPlugin.objects.using(db_alias).get(pk=1).delete()
    EmailTemplate.objects.using(db_alias).get(pk=1).delete()
    HookPlugin.objects.using(db_alias).get(id=1).delete()


class Migration(migrations.Migration):
    dependencies = [
        ('EmailAlertHookPlugin', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_func),
    ]
