# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-12-12 22:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('EmailAlertHookPlugin', '0002_auto_20191212_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailalerthookplugin',
            name='recipients',
            field=models.CharField(blank=True,
                                   help_text='Email addresses that will receive the alerts.  Separate with a comma.',
                                   max_length=256, verbose_name='Recipients List'),
        ),
    ]
