# Generated by Django 3.0.6 on 2020-05-29 23:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0002_auto_20191207_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sla',
            name='crittpl',
            field=models.ForeignKey(blank=True, default=None, help_text='Template to use when sending out critical emails when the SLA goes under the critical threshold.', limit_choices_to={'event': 'crit', 'obj': 'sla'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='slacrittpl', to='scheduler.Template', verbose_name='Critical template'),
        ),
        migrations.AlterField(
            model_name='sla',
            name='oktpl',
            field=models.ForeignKey(blank=True, default=None, help_text='Template to use when sending out recovery emails.', limit_choices_to={'event': 'ok', 'obj': 'sla'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='slaoktpl', to='scheduler.Template', verbose_name='Recovery template'),
        ),
        migrations.AlterField(
            model_name='sla',
            name='warntpl',
            field=models.ForeignKey(blank=True, default=None, help_text='Template to use when sending out warning emails when the SLA is being affected.', limit_choices_to={'event': 'warn', 'obj': 'sla'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='slawarntpl', to='scheduler.Template', verbose_name='Warning template'),
        ),
        migrations.AlterField(
            model_name='thresholds',
            name='crittpl',
            field=models.ForeignKey(blank=True, default=None, help_text='Template to use when sending out critical emails.', limit_choices_to={'event': 'crit', 'obj': 'thold'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='crittpl', to='scheduler.Template', verbose_name='Critical template'),
        ),
        migrations.AlterField(
            model_name='thresholds',
            name='errtpl',
            field=models.ForeignKey(blank=True, default=None, help_text='Template to use when sending out error emails.', limit_choices_to={'event': 'err', 'obj': 'thold'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='errtpl', to='scheduler.Template', verbose_name='Error template'),
        ),
        migrations.AlterField(
            model_name='thresholds',
            name='oktpl',
            field=models.ForeignKey(blank=True, default=None, help_text='Template to use when sending out recovery emails.', limit_choices_to={'event': 'ok', 'obj': 'thold'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='oktpl', to='scheduler.Template', verbose_name='Recovery template'),
        ),
        migrations.AlterField(
            model_name='thresholds',
            name='warntpl',
            field=models.ForeignKey(blank=True, default=None, help_text='Template to use when sending out warning emails.', limit_choices_to={'event': 'warn', 'obj': 'thold'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='warntpl', to='scheduler.Template', verbose_name='Warning template'),
        ),
    ]
