# Generated by Django 3.1.6 on 2021-02-06 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0003_auto_20200529_2351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thresholds',
            name='boolbad',
            field=models.BooleanField(default=None, help_text='For Boolean checks, If seen, this affects the SLA.  All other values OK.  Leave UNKOWN to disable.', null=True, verbose_name='BOOL Bad'),
        ),
        migrations.AlterField(
            model_name='thresholds',
            name='boolgood',
            field=models.BooleanField(default=None, help_text='For Boolean checks, This is the expected value.  Anything else affects the SLA.  Leave UNKOWN to disable', null=True, verbose_name='BOOL Good'),
        ),
        migrations.AlterField(
            model_name='thresholds',
            name='boolwarn',
            field=models.BooleanField(default=None, help_text='For Boolean checks, If seen, this triggers a warning email.  Leave UNKOWN to disable.', null=True, verbose_name='BOOL Warn'),
        ),
    ]
