# Generated by Django 3.0.6 on 2020-05-29 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardDisplayPlugin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.SlugField(blank=True, help_text='Internal name, leave empty to autopopulate.', max_length=64, unique=True, verbose_name='Name')),
                ('title', models.CharField(help_text='Verbose name for display purposes', max_length=256, verbose_name='Title')),
                ('logo', models.CharField(blank=True, help_text='Enter the path to your logo relative to /static/', max_length=256, verbose_name='Company Logo')),
                ('slogan', models.CharField(blank=True, help_text='Tag Line on the dashboard.', max_length=1024, verbose_name='Company Slogan')),
                ('template', models.CharField(blank=True, help_text='On-disk template prefix.  There must be one template per type.', max_length=128, verbose_name='Template Prefix')),
            ],
            options={
                'verbose_name': 'Dashboard',
                'verbose_name_plural': 'Dashboard Widgets',
            },
        ),
    ]
