# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-12-07 21:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historical',
            name='exportedk',
        ),
        migrations.RemoveField(
            model_name='hostchecks',
            name='statsinterval',
        ),
        migrations.RemoveField(
            model_name='hostchecks',
            name='status',
        ),
        migrations.RemoveField(
            model_name='sla',
            name='data',
        ),
    ]
